/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestContract } from "./TestContract";

export { TestContract__factory } from "./factories/TestContract__factory";
